apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true
  auth:
    secret_token: ""
    api_key:
      enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "apm-%{[observer.version]}-sourcemap"
      when.contains:
        processor.event: "sourcemap"
    - index: "apm-%{[observer.version]}-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"
    - index: "apm-%{[observer.version]}-transaction-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "transaction"
    - index: "apm-%{[observer.version]}-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"
    - index: "apm-%{[observer.version]}-metric-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "metric"
    - index: "apm-%{[observer.version]}-profile-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "profile"

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/apm-server
  name: apm-server
  keepfiles: 7
  permissions: 0644

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]