# Generated by Django 4.2.23 on 2025-07-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        help_text="Age range (e.g., '0 - 2', '3 - 5')", max_length=20
                    ),
                ),
                (
                    "common_label",
                    models.CharField(
                        help_text="Common label for this age group (e.g., 'Board-book / Infant', 'Picture-book (Pre-K)')",
                        max_length=50,
                    ),
                ),
                (
                    "typical_traits",
                    models.TextField(
                        help_text="Typical story and format traits for this age group"
                    ),
                ),
                (
                    "classic_examples",
                    models.TextField(
                        help_text="Classic examples of stories for this age group"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Age Group",
                "verbose_name_plural": "Age Groups",
                "ordering": ["age_range"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "topic",
                    models.CharField(
                        help_text="The main topic of the story", max_length=255
                    ),
                ),
                (
                    "hero",
                    models.CharField(
                        help_text="The main character of the story", max_length=255
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr-FR",
                        help_text="Language code (e.g., fr-FR, en-US)",
                        max_length=10,
                    ),
                ),
                (
                    "total_duration",
                    models.IntegerField(
                        default=0, help_text="Total duration of all chapters in seconds"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("tenant_only", "Tenant Only"),
                            ("private", "Private"),
                        ],
                        default="tenant_only",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=True, help_text="For AI Act compliance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "age_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target age group for this story",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stories",
                        to="stories.agegroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(help_text="The chapter text")),
                (
                    "place",
                    models.CharField(
                        help_text="The place where the chapter takes place",
                        max_length=255,
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        help_text="The tool used in the chapter", max_length=255
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="The order of the chapter in the story"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "chapters",
                "ordering": ["order"],
                "unique_together": {("story", "order")},
            },
        ),
    ]
