# Generated by Django 4.2.23 on 2025-07-14 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the story", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="A brief description of the story"),
                ),
                (
                    "age_group",
                    models.CharField(
                        help_text="The age group for the story", max_length=255
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="The main topic of the story", max_length=255
                    ),
                ),
                (
                    "hero",
                    models.CharField(
                        help_text="The main character of the story", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(help_text="The chapter text")),
                (
                    "place",
                    models.CharField(
                        help_text="The place where the chapter takes place",
                        max_length=255,
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        help_text="The tool used in the chapter", max_length=255
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="The order of the chapter in the story"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="stories.story",
                    ),
                ),
            ],
        ),
    ]
