# Generated by Django 4.2.23 on 2025-07-06 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("content", models.TextField(help_text="The story text")),
                (
                    "language",
                    models.CharField(
                        default="fr-FR",
                        help_text="Language code (e.g., fr-FR, en-US)",
                        max_length=10,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("0-3", "0-3 years"),
                            ("4-6", "4-6 years"),
                            ("7-9", "7-9 years"),
                            ("10-12", "10-12 years"),
                            ("13+", "13+ years"),
                        ],
                        default="4-6",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("tenant_only", "Tenant Only"),
                            ("private", "Private"),
                        ],
                        default="tenant_only",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=True, help_text="For AI Act compliance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
