FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements/requirements-base.txt requirements/requirements-monitoring.txt requirements/requirements-web.txt requirements/requirements-dev.txt ./
RUN pip install --upgrade pip \
    && pip install -r ./requirements-dev.txt

# Copy project
COPY . .

# Expose port
EXPOSE 8000

# Run the command
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
