FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Install system dependencies including ffmpeg
RUN apt-get update
RUN apt-get install -y ffmpeg
RUN rm -rf /var/lib/apt/lists/*


# Create media/hls directory and set permissions
RUN mkdir -p /app/media/hls && chmod -R 777 /app/media

# Install Python dependencies
COPY requirements/requirements-ai.txt requirements/requirements-ai.txt
COPY requirements/requirements-base.txt  requirements/requirements-base.txt
COPY requirements/requirements-celery.txt requirements/requirements-celery.txt
COPY requirements/requirements-dev.txt requirements/requirements-dev.txt
COPY requirements/requirements-web.txt requirements/requirements-web.txt

RUN pip install --no-cache-dir -r requirements/requirements-ai.txt
RUN pip install --no-cache-dir -r requirements/requirements-base.txt
RUN pip install --no-cache-dir -r requirements/requirements-celery.txt
RUN pip install --no-cache-dir -r requirements/requirements-dev.txt
RUN pip install --no-cache-dir -r requirements/requirements-web.txt
